import Foundation
import XCTest
@testable import BeetCode

/// Full-model K=8 validation.  The fixture is generated by mlx-lm 0.31.1
/// from the same installed quantized artifact and is deliberately kept out of
/// the repository because it is host-specific diagnostic data.  Normal test
/// runs skip this gate; CI or a target-Mac validation run opts in explicitly.
final class QwenStreamLongParityTests: XCTestCase {
    private struct Reference: Decodable {
        let artifactRevision: String
        let mlxLM: String
        let mlx: String
        let device: String
        let stateDType: String?
        let promptTokenIDs: [Int]
        let promptTokenCount: Int
        let promptSHA256: String
        let generatedTokenIDs: [Int]
        let stopReason: String
        let finalConsumedPosition: Int
    }

    /// Schema emitted by scripts/qwen35-bounded-oracle.py.  The reference
    /// stores only selected state/router summaries; the continuation cache is
    /// kept outside the test bundle and is never committed to the repository.
    private struct BoundedReference: Decodable {
        let artifactRevision: String
        let mlxLM: String
        let mlx: String
        let device: String
        let stateDType: String?
        let promptTokenIDs: [Int]
        let promptTokenCount: Int
        let promptSHA256: String
        let generatedTokenIDs: [Int]
        let stopReason: String
        let finalConsumedPosition: Int
        let checkpoints: [BoundedStage]
    }

    private struct BoundedStage: Decodable {
        let stage: String
        let positionBefore: Int
        let positionAfter: Int
        let inputToken: Int?
        let predictedToken: Int
        let router: [BoundedRouter]
        let layers: [BoundedLayer]
        let cache: [BoundedCache]
    }

    private struct BoundedRouter: Decodable {
        let layer: Int
        let position: Int
        let expertIDs: [Int]
        let scores: [Float]
    }

    private struct BoundedLayer: Decodable {
        let layer: Int
        let hidden: BoundedArray?
    }

    private struct BoundedCache: Decodable {
        let layer: Int
        let type: String
        let offset: Int
        let state: [BoundedArray?]
    }

    private struct BoundedArray: Decodable {
        let shape: [Int]
        let dtype: String
        let sample: [Float]
    }

    private struct RouterKey: Hashable {
        let layer: Int
        let position: Int
    }

    func testOptInLongGreedyCachedDecodeParity() async throws {
        guard ProcessInfo.processInfo.environment["BEETCODE_QWEN35_LONG_PARITY"] == "1" else {
            throw XCTSkip("Set BEETCODE_QWEN35_LONG_PARITY=1 for the independent 64+ token oracle.")
        }
        let path = ProcessInfo.processInfo.environment["BEETCODE_QWEN35_LONG_REFERENCE"]
            ?? "/tmp/qwen35-k8-long-reference-q21.json"
        guard FileManager.default.fileExists(atPath: path) else {
            throw XCTSkip("Pinned long-generation reference is not present at \(path).")
        }
        let reference = try JSONDecoder().decode(
            Reference.self,
            from: Data(contentsOf: URL(fileURLWithPath: path)))
        XCTAssertEqual(reference.artifactRevision, QwenStreamArtifact.revision)
        XCTAssertEqual(reference.mlxLM, "0.31.1")
        XCTAssertEqual(reference.mlx, "0.32.2")
        XCTAssertEqual(reference.device, "cpu")
        XCTAssertEqual(reference.promptTokenIDs.count, reference.promptTokenCount)
        XCTAssertGreaterThanOrEqual(reference.generatedTokenIDs.count, 64)

        let directory = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Application Support/BeetCode/Models", isDirectory: true)
            .appendingPathComponent(QwenStreamArtifact.modelID, isDirectory: true)
        guard FileManager.default.fileExists(atPath: directory.path) else {
            throw XCTSkip("Pinned Qwen3.5-35B-A3B artifact is not installed.")
        }

        let engine = QwenStreamingEngine(gate: GenerationGate())
        try await engine.load(
            directory: directory,
            modelID: QwenStreamArtifact.modelID,
            diskBytes: QwenStreamArtifact.downloadBytes,
            contextSize: 4096)
        defer { Task { await engine.unload() } }

        let run = try await engine.debugGreedy(
            tokenIDs: reference.promptTokenIDs,
            maxTokens: reference.generatedTokenIDs.count)
        XCTAssertEqual(run.generatedTokenIDs, reference.generatedTokenIDs,
                       "first differing generated-token index: \(firstDifference(run.generatedTokenIDs, reference.generatedTokenIDs).map(String.init) ?? "none")")
        XCTAssertEqual(run.stopReason, reference.stopReason)
        XCTAssertEqual(run.finalConsumedPosition, reference.finalConsumedPosition)
        XCTAssertGreaterThanOrEqual(run.generatedTokenIDs.count, 64)
        XCTAssertEqual(run.cachedDecodeCallCount, run.generatedTokenIDs.count,
                       "the diagnostic path feeds each emitted token once")
        XCTAssertEqual(run.decodeEmissionCallCount, max(0, run.generatedTokenIDs.count - 1),
                       "ordinary decode intervals exclude the first prefill-selected token")
        XCTAssertEqual(run.finalStateProbeCallCount,
                       run.generatedTokenIDs.isEmpty ? 0 : 1,
                       "the last emitted-token feed is the single final-state probe")

        let expectedSteps = [-1, 1, 2, 4, 8, 16, 32, 64].filter {
            $0 == -1 || $0 <= run.generatedTokenIDs.count
        }
        XCTAssertEqual(run.checkpoints.map(\.decodeStep), expectedSteps)
        for checkpoint in run.checkpoints {
            XCTAssertEqual(checkpoint.cache.layers.count, 40, "cache layer count at step \(checkpoint.decodeStep)")
            let expectedOffset = reference.promptTokenCount + max(0, checkpoint.decodeStep)
            // Mamba/ArraysCache carries consumed position in its recurrent
            // state and intentionally reports offset zero. KVCache carries
            // the logical attention length in offset. Treating both as an
            // attention offset made this diagnostic reject a valid cache
            // schema before it reached the actual parity assertions.
            for layer in checkpoint.cache.layers {
                let expected = layer.kind.hasPrefix("GatedDeltaNet/") ? 0 : expectedOffset
                XCTAssertEqual(layer.offset, expected,
                               "cache offset mismatch at layer \(layer.layer), step \(checkpoint.decodeStep)")
            }
            XCTAssertEqual(checkpoint.layerSnapshots.map(\.layer), [0, 19, 39])
        }

        let router = try XCTUnwrap(run.router)
        XCTAssertFalse(router.records.isEmpty)
        XCTAssertTrue(router.isComplete)
        for record in router.records {
            XCTAssertTrue([0, 19, 39].contains(record.layer))
            for ids in record.expertIDs {
                XCTAssertEqual(ids.count, QwenStreamArtifact.routingK)
                XCTAssertEqual(Set(ids).count, QwenStreamArtifact.routingK)
                XCTAssertTrue(ids.allSatisfy { (0..<QwenStreamArtifact.expertCount).contains($0) })
            }
            for scores in record.scores {
                XCTAssertEqual(scores.count, QwenStreamArtifact.routingK)
                XCTAssertTrue(scores.allSatisfy(\.isFinite))
            }
        }

        let outPath = ProcessInfo.processInfo.environment["BEETCODE_QWEN35_NATIVE_DEBUG"]
            ?? "/tmp/qwen35-k8-native-debug-q21.json"
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        try encoder.encode(run).write(to: URL(fileURLWithPath: outPath), options: .atomic)
        print("[qwen-long-parity] prompt=\(reference.promptTokenCount) generated=\(run.generatedTokenIDs.count) stop=\(run.stopReason) checkpoints=\(run.checkpoints.count) routerRecords=\(router.records.count) output=\(outPath)")
    }

    /// Compares the disposable process-per-stage oracle with native cached
    /// execution.  This is intentionally opt-in because it loads the real
    /// 35B artifact and is a target-Mac validation gate, never a normal unit
    /// test.  The numeric bounds below are frozen before a run: router IDs
    /// must be exact; sampled state/logit summaries allow only the observed
    /// quantized-kernel drift after shape and position equality.
    func testOptInBoundedReferenceParity() async throws {
        guard ProcessInfo.processInfo.environment["BEETCODE_QWEN35_BOUNDED_PARITY"] == "1" else {
            throw XCTSkip("Set BEETCODE_QWEN35_BOUNDED_PARITY=1 for the guarded independent oracle.")
        }
        let path = ProcessInfo.processInfo.environment["BEETCODE_QWEN35_BOUNDED_REFERENCE"]
            ?? "/tmp/qwen35-k8-q22/reference.json"
        guard FileManager.default.fileExists(atPath: path) else {
            throw XCTSkip("Bounded reference is not present at \(path).")
        }
        let reference = try JSONDecoder().decode(
            BoundedReference.self,
            from: Data(contentsOf: URL(fileURLWithPath: path)))
        XCTAssertEqual(reference.artifactRevision, QwenStreamArtifact.revision)
        XCTAssertEqual(reference.mlxLM, "0.31.1")
        XCTAssertEqual(reference.mlx, "0.32.2")
        XCTAssertEqual(reference.device, "cpu")
        XCTAssertEqual(reference.promptTokenIDs.count, reference.promptTokenCount)
        XCTAssertGreaterThan(reference.generatedTokenIDs.count, 0)

        let directory = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Application Support/BeetCode/Models", isDirectory: true)
            .appendingPathComponent(QwenStreamArtifact.modelID, isDirectory: true)
        guard FileManager.default.fileExists(atPath: directory.path) else {
            throw XCTSkip("Pinned Qwen3.5-35B-A3B artifact is not installed.")
        }

        let engine = QwenStreamingEngine(gate: GenerationGate())
        try await engine.load(
            directory: directory,
            modelID: QwenStreamArtifact.modelID,
            diskBytes: QwenStreamArtifact.downloadBytes,
            contextSize: 4096)
        defer { Task { await engine.unload() } }

        let run = try await engine.debugGreedy(
            tokenIDs: reference.promptTokenIDs,
            maxTokens: reference.generatedTokenIDs.count)
        XCTAssertEqual(run.generatedTokenIDs, reference.generatedTokenIDs,
                       "first differing generated-token index: \(firstDifference(run.generatedTokenIDs, reference.generatedTokenIDs).map(String.init) ?? "none")")
        XCTAssertEqual(run.stopReason, reference.stopReason)
        XCTAssertEqual(run.finalConsumedPosition, reference.finalConsumedPosition)

        compareBoundedCheckpoints(reference: reference, native: run)
        compareBoundedRouter(reference: reference, native: run)
        compareBoundedState(reference: reference, native: run)
        print("[qwen-bounded-parity] prompt=\(reference.promptTokenCount) generated=\(run.generatedTokenIDs.count) stop=\(run.stopReason) checkpoints=\(run.checkpoints.count)")
    }

    func testOptInLifecycleResourceMatrix() async throws {
        guard ProcessInfo.processInfo.environment["BEETCODE_QWEN35_Q21_LIFECYCLE"] == "1" else {
            throw XCTSkip("Set BEETCODE_QWEN35_Q21_LIFECYCLE=1 for the target-Mac lifecycle matrix.")
        }
        let directory = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Application Support/BeetCode/Models", isDirectory: true)
            .appendingPathComponent(QwenStreamArtifact.modelID, isDirectory: true)
        guard FileManager.default.fileExists(atPath: directory.path) else {
            throw XCTSkip("Pinned Qwen3.5-35B-A3B artifact is not installed.")
        }
        let engine = QwenStreamingEngine(gate: GenerationGate())
        try await engine.load(directory: directory, modelID: QwenStreamArtifact.modelID,
                              diskBytes: QwenStreamArtifact.downloadBytes, contextSize: 4096)
        let reference = try loadShortReferenceTokenIDs()
        _ = try await engine.debugGreedy(tokenIDs: reference, maxTokens: 2)
        var state = await engine.debugQuiescence()
        XCTAssertFalse(state.ownerActive)
        XCTAssertFalse(state.poolBusy)
        XCTAssertGreaterThanOrEqual(state.poolCapacitySlots, QwenStreamArtifact.routingK)

        await engine.unload()
        await engine.unload()
        try await engine.load(directory: directory, modelID: QwenStreamArtifact.modelID,
                              diskBytes: QwenStreamArtifact.downloadBytes, contextSize: 4096)
        _ = try await engine.debugGreedy(tokenIDs: reference, maxTokens: 2)
        state = await engine.debugQuiescence()
        XCTAssertFalse(state.ownerActive)
        XCTAssertFalse(state.poolBusy)
        await engine.unload()
    }

    private func loadShortReferenceTokenIDs() throws -> [Int] {
        let path = ProcessInfo.processInfo.environment["BEETCODE_QWEN35_LONG_REFERENCE"]
            ?? "/tmp/qwen35-k8-long-reference-q21.json"
        let data = try Data(contentsOf: URL(fileURLWithPath: path))
        struct Prompt: Decodable { let promptTokenIDs: [Int] }
        return try JSONDecoder().decode(Prompt.self, from: data).promptTokenIDs
    }

    private func firstDifference(_ lhs: [Int], _ rhs: [Int]) -> Int? {
        for index in 0..<min(lhs.count, rhs.count) where lhs[index] != rhs[index] {
            return index
        }
        return lhs.count == rhs.count ? nil : min(lhs.count, rhs.count)
    }

    private func compareBoundedCheckpoints(reference: BoundedReference, native: QwenStreamDebugRun) {
        let referenceByStep = Dictionary(uniqueKeysWithValues: reference.checkpoints.map { stage in
            (stageStep(stage, promptCount: reference.promptTokenCount), stage)
        })
        for checkpoint in native.checkpoints {
            guard let stage = referenceByStep[checkpoint.decodeStep] else {
                XCTFail("bounded reference is missing checkpoint \(checkpoint.decodeStep)")
                continue
            }
            XCTAssertEqual(stage.positionAfter,
                           reference.promptTokenCount + max(0, checkpoint.decodeStep),
                           "reference position at step \(checkpoint.decodeStep)")
            XCTAssertTrue(checkpoint.cache.layers.allSatisfy { $0.offset == stage.positionAfter },
                          "native cache position at step \(checkpoint.decodeStep)")
            XCTAssertEqual(checkpoint.layerSnapshots.map(\.layer), [0, 19, 39])
            XCTAssertEqual(stage.layers.map(\.layer), [0, 19, 39])
            XCTAssertEqual(stage.predictedToken, checkpoint.predictedToken,
                           "checkpoint greedy token at step \(checkpoint.decodeStep)")
        }
    }

    private func compareBoundedRouter(reference: BoundedReference, native: QwenStreamDebugRun) {
        guard let trace = native.router else {
            XCTFail("native router trace is missing")
            return
        }
        let referenceRecords = reference.checkpoints
            .flatMap(\.router)
            .reduce(into: [RouterKey: BoundedRouter]()) { records, record in
                records[RouterKey(layer: record.layer, position: record.position)] = record
            }
        let nativeRecords = trace.records.reduce(into: [RouterKey: ([Int], [Float])]()) { records, record in
            for (index, position) in record.positions.enumerated()
                where index < record.expertIDs.count && index < record.scores.count {
                records[RouterKey(layer: record.layer, position: position)] =
                    (record.expertIDs[index], record.scores[index])
            }
        }
        let sampledSteps = [-1, 1, 8, 16, 32, 64].filter {
            $0 == -1 || $0 <= reference.generatedTokenIDs.count
        }
        for step in sampledSteps {
            let position = step < 0
                ? reference.promptTokenCount - 1
                : reference.promptTokenCount + step - 1
            for layer in [0, 19, 39] {
                let key = RouterKey(layer: layer, position: position)
                guard let expected = referenceRecords[key] else {
                    XCTFail("reference router record missing layer=\(layer) position=\(position)")
                    continue
                }
                guard let actual = nativeRecords[key] else {
                    XCTFail("native router record missing layer=\(layer) position=\(position)")
                    continue
                }
                XCTAssertEqual(actual.0, expected.expertIDs,
                               "router K8 IDs at layer=\(layer) position=\(position)")
                XCTAssertLessThanOrEqual(relativeL2(actual.1, expected.scores), 0.03,
                                         "router score relL2 at layer=\(layer) position=\(position)")
                XCTAssertLessThanOrEqual(maxAbsDifference(actual.1, expected.scores), 0.05,
                                         "router score maxAbs at layer=\(layer) position=\(position)")
            }
        }
    }

    private func compareBoundedState(reference: BoundedReference, native: QwenStreamDebugRun) {
        let referenceByStep = Dictionary(uniqueKeysWithValues: reference.checkpoints.map { stage in
            (stageStep(stage, promptCount: reference.promptTokenCount), stage)
        })
        for checkpoint in native.checkpoints {
            guard let stage = referenceByStep[checkpoint.decodeStep] else { continue }
            let expectedCaches = Dictionary(uniqueKeysWithValues: stage.cache.map { ($0.layer, $0) })
            let actualCaches = Dictionary(uniqueKeysWithValues: checkpoint.cache.layers.map { ($0.layer, $0) })
            for layer in [0, 19, 39] {
                guard let expected = expectedCaches[layer], let actual = actualCaches[layer] else {
                    XCTFail("cache layer \(layer) missing at step \(checkpoint.decodeStep)")
                    continue
                }
                let expectedOffset = expected.type.hasPrefix("ArraysCache") ? 0 : expected.offset
                XCTAssertEqual(actual.offset, expectedOffset,
                               "cache offset layer=\(layer) step=\(checkpoint.decodeStep)")
                XCTAssertEqual(actual.state.count, expected.state.count,
                               "cache state count layer=\(layer) step=\(checkpoint.decodeStep)")
                for index in 0..<min(actual.state.count, expected.state.count) {
                    guard let expectedArray = expected.state[index] else { continue }
                    let actualArray = actual.state[index]
                    XCTAssertEqual(actualArray.shape, expectedArray.shape,
                                   "cache shape layer=\(layer) state=\(index) step=\(checkpoint.decodeStep)")
                    XCTAssertLessThanOrEqual(relativeL2(actualArray.sample, expectedArray.sample), 0.08,
                                             "cache relL2 layer=\(layer) state=\(index) step=\(checkpoint.decodeStep)")
                    XCTAssertLessThanOrEqual(maxAbsDifference(actualArray.sample, expectedArray.sample), 0.25,
                                             "cache maxAbs layer=\(layer) state=\(index) step=\(checkpoint.decodeStep)")
                }
            }
            let expectedLayers = Dictionary(uniqueKeysWithValues: stage.layers.map { ($0.layer, $0) })
            let actualLayers = Dictionary(uniqueKeysWithValues: checkpoint.layerSnapshots.map { ($0.layer, $0) })
            for layer in [0, 19, 39] {
                guard let expected = expectedLayers[layer]?.hidden,
                      let actual = actualLayers[layer]?.hidden else { continue }
                XCTAssertEqual(actual.shape, expected.shape,
                               "hidden shape layer=\(layer) step=\(checkpoint.decodeStep)")
                XCTAssertLessThanOrEqual(relativeL2(actual.sample, expected.sample), 0.08,
                                         "hidden relL2 layer=\(layer) step=\(checkpoint.decodeStep)")
                XCTAssertLessThanOrEqual(maxAbsDifference(actual.sample, expected.sample), 0.25,
                                         "hidden maxAbs layer=\(layer) step=\(checkpoint.decodeStep)")
            }
        }
    }

    private func stageStep(_ stage: BoundedStage, promptCount: Int) -> Int {
        stage.stage == "prefill" ? -1 : stage.positionAfter - promptCount
    }

    private func relativeL2(_ lhs: [Float], _ rhs: [Float]) -> Double {
        guard !lhs.isEmpty, lhs.count == rhs.count else { return .infinity }
        var numerator = 0.0
        var denominator = 0.0
        for (left, right) in zip(lhs, rhs) {
            let difference = Double(left) - Double(right)
            numerator += difference * difference
            denominator += Double(right) * Double(right)
        }
        return sqrt(numerator) / max(sqrt(denominator), 1e-12)
    }

    private func maxAbsDifference(_ lhs: [Float], _ rhs: [Float]) -> Double {
        guard lhs.count == rhs.count else { return .infinity }
        return zip(lhs, rhs).map { abs(Double($0) - Double($1)) }.max() ?? 0
    }
}
