import Foundation
import XCTest
@testable import BeetCode

/// Opt-in full-model logit checks. The expected values were generated by the
/// pinned upstream MLX-LM Qwen3.5 implementation against the same quantized
/// artifact, using lazy safetensors on CPU so the 16 GB host never loads a
/// second resident checkpoint. The normal suite skips this multi-minute gate.
final class QwenStreamFullParityTests: XCTestCase {
    private struct FixtureFile: Decodable {
        let artifactRevision: String
        let mlxLM: String
        let mlx: String
        let device: String
        let fixtures: [Fixture]
    }

    private struct Fixture: Decodable {
        let name: String
        let tokenIDs: [Int]
        let topIDs: [Int]
        let topLogits: [Float]
        let argmax: Int
    }

    func testOptInFullModelLogitParity() async throws {
        guard ProcessInfo.processInfo.environment["BEETCODE_QWEN35_FULL_PARITY"] == "1" else {
            throw XCTSkip("Set BEETCODE_QWEN35_FULL_PARITY=1 to run the independent full-model oracle.")
        }
        let fixtureURL = try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: "Qwen35K8Reference", withExtension: "json"))
        let fixture = try JSONDecoder().decode(FixtureFile.self, from: Data(contentsOf: fixtureURL))
        XCTAssertEqual(fixture.artifactRevision, QwenStreamArtifact.revision)
        XCTAssertEqual(fixture.device, "cpu")
        XCTAssertFalse(fixture.mlxLM.isEmpty)
        XCTAssertFalse(fixture.mlx.isEmpty)

        let directory = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Application Support/BeetCode/Models", isDirectory: true)
            .appendingPathComponent(QwenStreamArtifact.modelID, isDirectory: true)
        guard FileManager.default.fileExists(atPath: directory.path) else {
            throw XCTSkip("Pinned Qwen3.5-35B-A3B artifact is not installed.")
        }

        let limit = Int(ProcessInfo.processInfo.environment["BEETCODE_QWEN35_PARITY_LIMIT"] ?? "0") ?? 0
        let selected = limit > 0 ? Array(fixture.fixtures.prefix(limit)) : fixture.fixtures
        let engine = QwenStreamingEngine(gate: GenerationGate())
        try await engine.load(
            directory: directory,
            modelID: QwenStreamArtifact.modelID,
            diskBytes: QwenStreamArtifact.downloadBytes,
            contextSize: 4096)
        defer { Task { await engine.unload() } }

        for expected in selected {
            let reset = await engine.resetApplicationExpertPool()
            XCTAssertTrue(reset, expected.name)
            let actual = try await engine.debugForward(tokenIDs: expected.tokenIDs)
            XCTAssertEqual(actual.count, 248_320, expected.name)
            let ids = actual.indices.sorted { actual[$0] > actual[$1] }.prefix(expected.topIDs.count)
            let actualIDs = Array(ids)
            let expectedByID = Dictionary(uniqueKeysWithValues: zip(expected.topIDs, expected.topLogits))
            let actualValues = expected.topIDs.map { actual[$0] }
            let squared = expected.topIDs.reduce(0.0) { partial, id in
                let delta = Double(actual[id]) - Double(expectedByID[id] ?? 0)
                return partial + delta * delta
            }
            let expectedNorm = sqrt(expected.topLogits.reduce(0.0) {
                $0 + Double($1) * Double($1)
            })
            let relL2 = sqrt(squared) / max(expectedNorm, 1e-12)
            let maxAbs = expected.topIDs
                .map { abs(Double(actual[$0]) - Double(expectedByID[$0] ?? 0)) }
                .max() ?? .infinity
            print("[qwen-full-parity] \(expected.name) ids=\(actualIDs) expected=\(expected.topIDs) values=\(actualValues) relL2=\(relL2) maxAbs=\(maxAbs)")
            // CPU/GPU MLX revisions can permute equal or near-equal tail
            // logits without changing greedy behavior. Require exact IDs when
            // they are separated from the top-k cutoff; allow only a bounded
            // cutoff tie, while retaining the frozen logit drift envelope.
            let expectedSet = Set(expected.topIDs)
            let actualSet = Set(actualIDs)
            if expectedSet != actualSet {
                let expectedMissing = expectedSet.subtracting(actualSet)
                let actualMissing = actualSet.subtracting(expectedSet)
                let cutoff = min(expected.topLogits.last ?? 0, actualIDs.map { actual[$0] }.min() ?? 0)
                let tieDrift = expectedMissing.allSatisfy {
                    abs(Double(expectedByID[$0] ?? 0) - Double(cutoff)) <= 0.5
                } && actualMissing.allSatisfy {
                    abs(Double(actual[$0]) - Double(cutoff)) <= 0.5
                }
                XCTAssertTrue(tieDrift, "\(expected.name) non-tied top-k ID drift")
                print("[qwen-full-parity] \(expected.name) cutoff-tie tail drift expectedMissing=\(expectedMissing) actualMissing=\(actualMissing)")
            }
            XCTAssertEqual(actualIDs.first, expected.argmax, expected.name)
            XCTAssertLessThan(relL2, 0.03, expected.name)
            XCTAssertLessThanOrEqual(maxAbs, 0.75, expected.name)
        }
    }
}
