import Foundation
import XCTest
@testable import BeetCode

/// Development diagnostic for the first mismatching hidden-state boundary.
/// The JSON input is generated by the independent Python/MLX oracle and is
/// intentionally kept outside the repository because it contains no model
/// weights but is only useful for one pinned host investigation.
final class QwenStreamLayerParityDiagnosticTests: XCTestCase {
    private struct Fixture: Decodable {
        let tokenIDs: [Int]
        let layers: [[Float]]
    }

    func testOptInFindsFirstLayerMismatch() async throws {
        guard ProcessInfo.processInfo.environment["BEETCODE_QWEN35_LAYER_PARITY"] == "1" else {
            throw XCTSkip("Set BEETCODE_QWEN35_LAYER_PARITY=1 for the first-layer mismatch diagnostic.")
        }
        let path = ProcessInfo.processInfo.environment["BEETCODE_QWEN35_LAYER_FIXTURE"]
            ?? "/tmp/qwen35-arithmetic-layer-fixture.json"
        guard FileManager.default.fileExists(atPath: path) else {
            throw XCTSkip("Independent layer fixture is not present at \(path).")
        }
        let fixture = try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: URL(fileURLWithPath: path)))
        let directory = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Application Support/BeetCode/Models", isDirectory: true)
            .appendingPathComponent(QwenStreamArtifact.modelID, isDirectory: true)
        let engine = QwenStreamingEngine(gate: GenerationGate())
        try await engine.load(
            directory: directory,
            modelID: QwenStreamArtifact.modelID,
            diskBytes: QwenStreamArtifact.downloadBytes,
            contextSize: 4096)
        let actual = try await engine.debugLayerForward(tokenIDs: fixture.tokenIDs)
        XCTAssertGreaterThanOrEqual(actual.count, fixture.layers.count)
        for (layerNumber, pair) in zip(actual, fixture.layers).enumerated() {
            guard pair.0.count == pair.1.count else {
                XCTFail("Layer \(layerNumber) shape mismatch")
                continue
            }
            let squared = zip(pair.0, pair.1).reduce(0.0) {
                let delta = Double($1.0) - Double($1.1)
                return $0 + delta * delta
            }
            let norm = sqrt(pair.1.reduce(0.0) { $0 + Double($1) * Double($1) })
            let relL2 = sqrt(squared) / max(norm, 1e-12)
            let maxAbs = zip(pair.0, pair.1).map { abs(Double($0.0) - Double($0.1)) }.max() ?? 0
            print("[qwen-layer-parity] layer=\(layerNumber) relL2=\(relL2) maxAbs=\(maxAbs)")
        }
        await engine.unload()
    }
}
